// Copyright 2021 Manna Harbour
// https://github.com/manna-harbour/miryoku
MIRYOKU_TAP=QWERTY 
MIRYOKU_EXTRA=QWERTY 
CONFIG_ZMK_DISPLAY_HIDE_MOMENTARY_LAYERS=y 
CONFIG_CUSTOM_WIDGET_LOGO_IMAGE_ZEN=n
CONFIG_CUSTOM_WIDGET_LOGO_IMAGE_ZMK=y
CONFIG_CUSTOM_WIDGET_LOGO_IMAGE_LPKB=n
CONFIG_CUSTOM_WIDGET_LOGO_IMAGE_MIRYOKU=y Miryoku logo.
CONFIG_IL0323_INVERT=y
