# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Example corne-ish_zen'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corne-ish_zen_left","corne-ish_zen_right"]'
      alphas: '["qwerty"]'
      nav: '["vi"]'
      clipboard: '["windows"]' 
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
      branches: '[
        "zmkfirmware/zmk/main krikun98/zmk/mouse-pr",
        "zmkfirmware/zmk/main ftc/zmk/mouse-ftc"
        "zmkfirmware/zmk/main ftc/zmk/mouse-ftc",
        "ftc/zmk/mouse-ftc"
      ]'
